language: python
python:
  - "2.7"
services:
  - "mysql"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
before_script:
  - "mysql -e 'CREATE DATABASE `what_manager2` COLLATE utf8_unicode_ci;'"
script:
  - "flake8 ."
  - "./manage.py test"
